[tool.black]
line-length = 88
target-version = ['py38']
skip-string-normalization = false
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
  | build
  | dist
  | __pycache__
  | .eggs
  | .mypy_cache
  | .pytest_cache
  | .ipynb_checkpoints
)/
'''

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
use_parentheses = true
force_grid_wrap = 0
ensure_newline_before_comments = true
known_first_party = ["utils"]
known_third_party = ["torch", "numpy", "munch"]
